# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2UzYWM5MmVlYzRiNjE2YjFlN2U1ODUxZThlMzE1ZThjNTBjM2I5M2Y0OTBiMWI5ZTlkMGRiODBiOTMxOWE1ZTVmNDNlYzBiNmUxNGUzMzc1NjgzYThiYzI3ZDE2ZTM5YTBhNDZhNDNkNzk3NDRiNmMwNmIzNjAxZTBlYzU2NmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
